# Generated by Django 5.0.2 on 2024-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
