# Generated by Django 5.0.2 on 2024-09-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenitiess",
            name="deskrisaun",
            field=models.TextField(),
        ),
    ]
