# Generated by Django 5.0.2 on 2024-09-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_reservated_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("occupied", "Occupied")],
                max_length=10,
            ),
        ),
    ]
