# Generated by Django 5.0.2 on 2024-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_room_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="images",
            field=models.ImageField(null=True, upload_to="room"),
        ),
    ]
