# Generated by Django 5.0.2 on 2024-05-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_room_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Occupied", "Occupied"),
                    ("Maintenance", "Maintenance"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RoomOccupied",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("La Ativo", "La Ativo")],
                        default="Ativo",
                        max_length=20,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomoccupiedguest",
                        to="apps.guest",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="Presu"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.room"
                    ),
                ),
            ],
        ),
    ]
