# Generated by Django 5.0.2 on 2024-09-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_alter_room_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenitiess",
            name="imajen",
        ),
    ]
