# Generated by Django 5.0.2 on 2024-05-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_remove_reservation_status_alter_room_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="guest",
            name="last_name",
        ),
    ]
