# Generated by Django 5.0.2 on 2024-09-25 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_remove_amenitiess_imajen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.room"
                    ),
                ),
            ],
        ),
    ]
