# Generated by Django 5.0.2 on 2024-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_rename_first_name_guest_name_remove_guest_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="address",
        ),
        migrations.AddField(
            model_name="guest",
            name="sex",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
