# Generated by Django 5.0.2 on 2024-08-23 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_alter_roomoccupied_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Reservated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.room"
                    ),
                ),
            ],
        ),
    ]
